### ISSUE TITLE
Nette/Deprecated Enviroment does not exist in download zip

### ISSUE THREAD

**Issue by martingold** [nette/examples#18]
When downloading zip package from [here](https://github.com/nette/nette/releases/download/v2.4.0/Nette-2.4-20170829.zip) and trying out examples it spits out [this](https://user-images.githubusercontent.com/15158789/30174093-30f7aa2e-93fa-11e7-986f-4f0e352be0e4.png) warning. This can be easily solved by not using NetteLoader at all and use composer autoload instead as in web-project and sandbox. It's not a problem since you have to do composer update even with the original approach.

Issue can be easily solved by substituting 
```
// Load Nette Framework
if (@!include __DIR__ . '/../../../Nette/loader.php') {
	die('Install Nette using `composer update`');
}
```
with
```
require __DIR__ . '/../vendor/autoload.php';
```

Issue is easily reproducable by doing these steps:
```
wget https://github.com/nette/nette/releases/download/v2.4.0/Nette-2.4-20170829.zip -O nette.zip
unzip nette.zip
cd Nette-2.4-20170829/examples/CD-collection/
composer update
php -S localhost:8000
```
and opening browser at http://localhost:800/www/index.php

I feel like it may have some side effects or break some intended behaviour, thus would not open PR but issue where we can have some discussion about this. Let me know if i should make PR.

**Comment by martingold** [comment]
I think its side effect of [this](https://github.com/nette/deprecated/commit/3e3882707af18975e0caeb560cef60dc95b718a5) commit

**Comment by dg** [comment]
It is bug in archive, I will reupload it.
